language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

deploy:
  provider: heroku
  api_key:
    secure: 2rBudh+oePpjXTSqRgPaMRYxnnuFcOIKNTXIFOF1Y5fjiizClmbmXwnXht0PORbXCARll0K72AsEImrWHkWeGJyCRD+9cMTAkTQ8jouaE/7L2u19yXaUKJhB6PN2s+qDa7RpfN7IKfiIfsQdzpeoOmldjB9mJADX9FUPld+RcEdNE48Ko/bFn5hsPF7SyLQpQ11dNiAzCCgmVCXIQhCTb55Qv0VL9oPjBhVgLlfX6hxaTRe4R5sQaarXB6RF8QQr4IM0OTq0g2PasLpp+r/BkLPuxlxAIDKdZ5ITforQ3SWFGjEnPBCgsWVpTkGnYZ5JUAwOTVpGx+pFc1Czh/apDSH4yoFD1R5cKUJE+NojO4KK1wT07f68QBvrxVpd8jJZnh22jgeVUih9sTTFK1U1MPeL+6cCLs0iMAlaAc9lE0MYy85MfpXuhEFOxmrXd4efyYdIAf8EBaGIphlijrf79NIRy2YsrgO1vbahUm/qsrNiEwfUApXyMZBcOMWmGGze+22AUtihxUMM00NjPzwQBYNj1EygOMEHHusl6UpUmRlvpt8cYxgC1kqOI/eVvW10RjecgIVu30zXmnpPrAZHK6mI8zSj+7dFsGgn/tBET3tHRXhiygHdInFrJ3WbRgguFQ4uK/vdXKig3otkrJFPfCjXuYngS7rSpULbyJhhsgM=
  app: hackathon-bitcoin-roulette
  on:
    repo: cassiolana/hackathon-bitcoin-roulette
